kind: pipeline
type: kubernetes
name: default
# volumes:
# - name: docker_sock
#   host:
#     path: /var/run/docker.sock
# steps:
# - name: test
#   image: docker
#   volumes:
#     - name: docker_sock
#       path: /var/run/docker.sock
#   commands:
#   - docker version
#   - env
steps:
  - name: deploy
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_token: ${KUBERNETES_TOKEN}
    # notice: no tls verification will be done, warning will is printed
    deployment: my-deployment
    repo: minazukie/play-wasm
    container: my-container
    namespace: prod
    commands:
    - kubectl apply -f k.yml
