kind: pipeline
type: kubernetes
name: default
# volumes:
# - name: docker_sock
#   host:
#     path: /var/run/docker.sock
# steps:
# - name: test
#   image: docker
#   volumes:
#     - name: docker_sock
#       path: /var/run/docker.sock
#   commands:
#   - docker version
#   - env
steps:
  - name: deploy
    user: root
    image: bitnami/kubectl
    volumes:
    - name: kube
      path: /.kube
    - name: minikube
      path: /.minikube
    commands:
    - chmod 666 /root
    - cd / && ls -la
    - kubectl get svc -n prod
      
volumes:
- name: kube
  host:
    path: /root/.kube  # kubeconfig 挂载位置
- name: minikube
  host:
    path: /root/.minikube
