kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  pull: if-not-exists
  image: docker
  volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  commands:
  - docker version
