kind: pipeline
type: kubernetes
name: default
# volumes:
# - name: docker_sock
#   host:
#     path: /var/run/docker.sock
# steps:
# - name: test
#   image: docker
#   volumes:
#     - name: docker_sock
#       path: /var/run/docker.sock
#   commands:
#   - docker version
#   - env
steps:
  - name: deploy
    image: boxboat/kubectl:1.18.1
    volumes:
    - name: kube
      path: /home/alpine/.kube
    - name: minikube
      path: /home/alpine/.minikube
    commands:
    - ls -la /home/.kube
    - kubectl get svc -n app
      
volumes:
- name: kube
  host:
    path: /home/mizki/.kube  # kubeconfig 挂载位置
- name: minikube
  host:
    path: /home/mizki/.minikube
