kind: pipeline
type: kubernetes
name: default
# volumes:
# - name: docker_sock
#   host:
#     path: /var/run/docker.sock
# steps:
# - name: test
#   image: docker
#   volumes:
#     - name: docker_sock
#       path: /var/run/docker.sock
#   commands:
#   - docker version
#   - env
steps:
  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: KUBERNETES_SERVER
      kubernetes_cert:
        from_secret: KUBERNETES_CERT
      kubernetes_token:
        from_secret: KUBERNETES_TOKEN
    commands:
      - kubectl get service -n drone
