kind: pipeline
type: kubernetes
name: default
# volumes:
# - name: docker_sock
#   host:
#     path: /var/run/docker.sock
# steps:
# - name: test
#   image: docker
#   volumes:
#     - name: docker_sock
#       path: /var/run/docker.sock
#   commands:
#   - docker version
#   - env
steps:
  - name: deploy
    image: boxboat/kubectl:1.18.1
    volumes:
    - name: kube
      path: /home/alpine/.kube
    commands:
    - ls -la /home/alpine/.kube
    - kubectl get svc -n app

volumes:
- name: kube
  host:
    path: /var/kubeconfig  # kubeconfig 挂载位置

