kind: pipeline
type: kubernetes
name: default
# volumes:
# - name: docker_sock
#   host:
#     path: /var/run/docker.sock
# steps:
# - name: test
#   image: docker
#   volumes:
#     - name: docker_sock
#       path: /var/run/docker.sock
#   commands:
#   - docker version
#   - env
steps:
  - name: deploy
    image: vallard/drone-kube
    template: k.yml
    namespace: prod
    server: https://172.104.76.190:8443
